-- Runs after contract.sql in the same psql session; no remote database.
begin;
update private.memory_publication_settings set reads_enabled=true;
select pg_temp.ok(public.read_memory_publication(current_setting('test.id')::uuid) is not null,'content review negative control: existing reader exposes unclassified board');
\ir content-review-candidate.sql
select pg_temp.ok((select content_policy_revision='UNCONFIGURED' from private.memory_publication_settings),'migration installs an unconfigured content policy');
select pg_temp.ok(public.read_memory_publication(current_setting('test.id')::uuid) is null,'migration closes previously readable unclassified board before any policy setup');
update private.memory_publication_settings set content_policy_revision='TEST_ONLY_CONTENT';
select set_config('test.content_hash',(select encode(sha256(convert_to(published_snapshot::text,'UTF8')),'hex') from private.memory_publications where id=current_setting('test.id')::uuid),true);
set local role anon;
select pg_temp.ok(public.read_memory_publication(current_setting('test.id')::uuid) is null,'unreviewed board hides metadata and cards');
select pg_temp.fails($q$select * from private.memory_content_reviews$q$,'permission denied','anonymous cannot read reviews');
reset role;
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
set local role authenticated;
select pg_temp.fails($q$select public.review_memory_publication_content(current_setting('test.id')::uuid,current_setting('test.content_hash'),'GENERAL',0,'TEST_ONLY_CONTENT')$q$,'MODERATOR_REQUIRED','owner cannot self-approve classification');
reset role;
insert into private.memory_moderators(user_id) values('11111111-1111-4111-8111-111111111111');
set local role authenticated;
\ir content-initial-contract.sql
select pg_temp.fails($q$select public.review_memory_publication_content(current_setting('test.id')::uuid,repeat('0',64),'GENERAL',0,'TEST_ONLY_CONTENT')$q$,'PUBLICATION_CONFLICT','unseen snapshot cannot be approved');
select pg_temp.ok(public.review_memory_publication_content(current_setting('test.id')::uuid,current_setting('test.content_hash'),'GENERAL',0,'TEST_ONLY_CONTENT')=1,'moderator approves exact snapshot');
select pg_temp.fails($q$select public.review_memory_publication_content(current_setting('test.id')::uuid,current_setting('test.content_hash'),'MATURE',0,'TEST_ONLY_CONTENT')$q$,'PUBLICATION_CONFLICT','stale moderation action rejected');
set local role anon;
select pg_temp.ok(public.read_memory_publication(current_setting('test.id')::uuid) is not null,'reviewed general board is readable through real RPC');
reset role;
update private.memory_publications set published_snapshot=jsonb_set(published_snapshot,'{title}','"Changed after review"') where id=current_setting('test.id')::uuid;
set local role anon;
select pg_temp.ok(public.read_memory_publication(current_setting('test.id')::uuid) is null,'changed title invalidates whole snapshot review');
reset role;
select set_config('test.content_hash',(select encode(sha256(convert_to(published_snapshot::text,'UTF8')),'hex') from private.memory_publications where id=current_setting('test.id')::uuid),true);
set local role authenticated;
select public.review_memory_publication_content(current_setting('test.id')::uuid,current_setting('test.content_hash'),'MATURE',1,'TEST_ONLY_CONTENT');
set local role anon;
select pg_temp.ok(public.read_memory_publication(current_setting('test.id')::uuid) is null,'mature board remains closed without adult eligibility implementation');
select pg_temp.fails($q$select private.read_memory_publication_before_content_review(current_setting('test.id')::uuid)$q$,'permission denied','anonymous cannot call original reader to bypass review');
reset role;
set local role authenticated;
select public.review_memory_publication_content(current_setting('test.id')::uuid,current_setting('test.content_hash'),'GENERAL',2,'TEST_ONLY_CONTENT');
select pg_temp.fails($q$delete from private.memory_content_review_audit$q$,'permission denied','moderator cannot erase classification audit');
reset role;
select pg_temp.ok((select count(*)=3 from private.memory_content_review_audit where target_kind='board' and target_id=current_setting('test.id')::uuid),'only successful classification changes produce audit records');
select pg_temp.ok((select bool_and(policy_revision='TEST_ONLY_CONTENT' and actor='11111111-1111-4111-8111-111111111111') from private.memory_content_review_audit),'audit binds policy and authenticated moderator');
update private.memory_publication_settings set content_policy_revision='TEST_ONLY_CONTENT_V2';
set local role anon;
select pg_temp.ok(public.read_memory_publication(current_setting('test.id')::uuid) is null,'new policy invalidates old general approval');
set local role authenticated;
select pg_temp.fails($q$select public.review_memory_publication_content(current_setting('test.id')::uuid,current_setting('test.content_hash'),'GENERAL',3,'TEST_ONLY_CONTENT')$q$,'CONTENT_POLICY_CHANGED','old reviewed policy cannot approve under current policy');
select pg_temp.fails($q$select public.review_memory_publication_content(current_setting('test.id')::uuid,current_setting('test.content_hash'),'GENERAL',3,null)$q$,'CONTENT_POLICY_CHANGED','missing policy is not inferred for reviewer');
select public.review_memory_publication_content(current_setting('test.id')::uuid,current_setting('test.content_hash'),'GENERAL',3,'TEST_ONLY_CONTENT_V2');
set local role anon;
select pg_temp.ok(public.read_memory_publication(current_setting('test.id')::uuid) is not null,'explicit current-policy re-review restores general read');
reset role;
\ir content-notice-contract.sql
update private.memory_publication_settings set reads_enabled=false;
set local role anon;
select pg_temp.ok(public.read_memory_publication(current_setting('test.id')::uuid) is null,'general approval does not bypass original kill switch');
reset role;
rollback;
