begin;
reset role;
\ir content-review-candidate.sql
update private.memory_publication_settings set content_policy_revision='TEST_ONLY_CONTENT';
select set_config('test.content_hash',(select encode(sha256(convert_to(published_snapshot::text,'UTF8')),'hex') from private.memory_publications where id=(current_setting('test.preview')::jsonb->>'id')::uuid),true);
set local role service_role;
select pg_temp.ok(public.resolve_memory_public_image((current_setting('test.preview')::jsonb->>'id')::uuid,(current_setting('test.reservation')::jsonb->>'id')::uuid,'thumb') is null,'unreviewed thumbnail denied even through delivery service role');
select pg_temp.ok(public.resolve_memory_public_image((current_setting('test.preview')::jsonb->>'id')::uuid,(current_setting('test.reservation')::jsonb->>'id')::uuid,'full') is null,'unreviewed full image denied through delivery resolver');
reset role;
insert into private.memory_moderators(user_id) values('11111111-1111-4111-8111-111111111111');
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
set local role authenticated;
select public.review_memory_publication_content((current_setting('test.preview')::jsonb->>'id')::uuid,current_setting('test.content_hash'),'GENERAL',0,'TEST_ONLY_CONTENT');
set local role service_role;
select pg_temp.ok(public.resolve_memory_public_image((current_setting('test.preview')::jsonb->>'id')::uuid,(current_setting('test.reservation')::jsonb->>'id')::uuid,'thumb')->>'path' like '%/thumb.webp','general review permits original thumbnail resolver');
select pg_temp.ok(public.resolve_memory_public_image((current_setting('test.preview')::jsonb->>'id')::uuid,(current_setting('test.reservation')::jsonb->>'id')::uuid,'full')->>'path' like '%/full.webp','general review permits original full resolver');
set local role authenticated;
select public.review_memory_publication_content((current_setting('test.preview')::jsonb->>'id')::uuid,current_setting('test.content_hash'),'MATURE',1,'TEST_ONLY_CONTENT');
reset role;
select set_config('test.image_review_case',(select case_id::text from private.memory_content_review_audit where target_id=(current_setting('test.preview')::jsonb->>'id')::uuid and revision=2),true);
set local role authenticated;
select pg_temp.ok(public.resolve_memory_content_review_image(current_setting('test.image_review_case')::uuid,current_setting('test.content_hash'),'TEST_ONLY_CONTENT',2,(current_setting('test.reservation')::jsonb->>'id')::uuid,'full')->>'path' like '%/full.webp','moderator can resolve exact mature review image');
select pg_temp.ok(public.resolve_memory_content_review_image(current_setting('test.image_review_case')::uuid,current_setting('test.content_hash'),'TEST_ONLY_CONTENT',2,(current_setting('test.reservation')::jsonb->>'id')::uuid,'thumb')->>'path' like '%/thumb.webp','moderator can resolve reviewed thumbnail');
select pg_temp.ok(public.resolve_memory_content_review_image(current_setting('test.image_review_case')::uuid,repeat('0',64),'TEST_ONLY_CONTENT',2,(current_setting('test.reservation')::jsonb->>'id')::uuid,'full') is null,'review image hash mismatch denied');
select pg_temp.ok(public.resolve_memory_content_review_image(current_setting('test.image_review_case')::uuid,current_setting('test.content_hash'),'OLD_POLICY',2,(current_setting('test.reservation')::jsonb->>'id')::uuid,'full') is null,'review image old policy denied');
select pg_temp.ok(public.resolve_memory_content_review_image(current_setting('test.image_review_case')::uuid,current_setting('test.content_hash'),'TEST_ONLY_CONTENT',1,(current_setting('test.reservation')::jsonb->>'id')::uuid,'full') is null,'review image old classification revision denied');
select pg_temp.ok(public.resolve_memory_content_review_image(current_setting('test.image_review_case')::uuid,current_setting('test.content_hash'),'TEST_ONLY_CONTENT',2,gen_random_uuid(),'full') is null,'unrelated asset cannot be resolved through review case');
reset role;
select set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',true);
set local role authenticated;
select pg_temp.fails($q$select public.resolve_memory_content_review_image(current_setting('test.image_review_case')::uuid,current_setting('test.content_hash'),'TEST_ONLY_CONTENT',2,(current_setting('test.reservation')::jsonb->>'id')::uuid,'full')$q$,'MODERATOR_REQUIRED','ordinary account cannot resolve moderator image');
set local role anon;
select pg_temp.fails($q$select public.resolve_memory_content_review_image(null,null,null,null,null,'full')$q$,'permission denied','anonymous cannot invoke moderator image resolver');
reset role;
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
set local role service_role;
select pg_temp.ok(public.resolve_memory_public_image((current_setting('test.preview')::jsonb->>'id')::uuid,(current_setting('test.reservation')::jsonb->>'id')::uuid,'thumb') is null,'reclassification closes previously readable thumbnail');
select pg_temp.ok(public.resolve_memory_public_image((current_setting('test.preview')::jsonb->>'id')::uuid,(current_setting('test.reservation')::jsonb->>'id')::uuid,'full') is null,'reclassification closes previously readable full image');
select pg_temp.fails($q$select private.read_memory_publication_before_content_review((current_setting('test.preview')::jsonb->>'id')::uuid)$q$,'permission denied','delivery service cannot call old reader to bypass classification');
reset role;
rollback;
