begin;
reset role;
update private.memory_publication_settings set reads_enabled=true,minihomes_enabled=true;
update private.memory_publication_accounts set hidden=false;
-- Restore only synthetic retired fixtures inside this rollback transaction, so
-- the embedded-board denial has a positive control rather than an empty board.
delete from private.memory_publication_delete_fences where user_id='11111111-1111-4111-8111-111111111111';
update private.memory_public_cards set revoked=false where user_id='11111111-1111-4111-8111-111111111111';
select pg_temp.ok(public.read_memory_minihome(current_setting('test.home')::uuid) is not null,'home negative control: original reader exposes unclassified nickname');
select pg_temp.ok(jsonb_array_length(public.read_memory_minihome(current_setting('test.home')::uuid)->'entries')>0,'home negative control contains an actually readable board');
\ir content-review-candidate.sql
update private.memory_publication_settings set content_policy_revision='TEST_ONLY_CONTENT';
select set_config('test.home_hash',(select encode(sha256(convert_to(published_selection::text,'UTF8')),'hex') from private.memory_minihomes where id=current_setting('test.home')::uuid),true);
set local role anon;
select pg_temp.ok(public.read_memory_minihome(current_setting('test.home')::uuid) is null,'unreviewed home conceals nickname and bio');
select pg_temp.fails($q$select private.read_memory_minihome_before_content_review(current_setting('test.home')::uuid)$q$,'permission denied','original home reader cannot bypass review');
reset role;
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
set local role authenticated;
select pg_temp.fails($q$select public.review_memory_minihome_content(current_setting('test.home')::uuid,current_setting('test.home_hash'),'GENERAL',0,'TEST_ONLY_CONTENT')$q$,'MODERATOR_REQUIRED','home owner cannot self approve');
reset role;
insert into private.memory_moderators(user_id) values('11111111-1111-4111-8111-111111111111');
set local role authenticated;
\ir content-home-queue-contract.sql
select pg_temp.fails($q$select public.review_memory_minihome_content(current_setting('test.home')::uuid,repeat('0',64),'GENERAL',0,'TEST_ONLY_CONTENT')$q$,'PUBLICATION_CONFLICT','home mismatched reviewed selection rejected');
select public.review_memory_minihome_content(current_setting('test.home')::uuid,current_setting('test.home_hash'),'GENERAL',0,'TEST_ONLY_CONTENT');
set local role anon;
select pg_temp.ok(public.read_memory_minihome(current_setting('test.home')::uuid)->>'nickname'='Public nickname','exact reviewed home nickname readable');
select pg_temp.ok(jsonb_array_length(public.read_memory_minihome(current_setting('test.home')::uuid)->'entries')=0,'home approval does not approve embedded boards');
reset role;
update private.memory_minihomes set published_selection=jsonb_set(published_selection,'{bio}','"Changed intro"') where id=current_setting('test.home')::uuid;
set local role anon;
select pg_temp.ok(public.read_memory_minihome(current_setting('test.home')::uuid) is null,'changed bio invalidates home classification');
reset role;
select set_config('test.home_hash',(select encode(sha256(convert_to(published_selection::text,'UTF8')),'hex') from private.memory_minihomes where id=current_setting('test.home')::uuid),true);
set local role authenticated;
select pg_temp.fails($q$select public.review_memory_minihome_content(current_setting('test.home')::uuid,current_setting('test.home_hash'),'GENERAL',0,'TEST_ONLY_CONTENT')$q$,'PUBLICATION_CONFLICT','home stale review rejected');
select public.review_memory_minihome_content(current_setting('test.home')::uuid,current_setting('test.home_hash'),'MATURE',1,'TEST_ONLY_CONTENT');
set local role anon;
select pg_temp.ok(public.read_memory_minihome(current_setting('test.home')::uuid) is null,'mature home stays closed without adult eligibility');
reset role;
select set_config('test.board_hash',(select encode(sha256(convert_to(published_snapshot::text,'UTF8')),'hex') from private.memory_publications where id=current_setting('test.board')::uuid),true);
set local role authenticated;
select public.review_memory_publication_content(current_setting('test.board')::uuid,current_setting('test.board_hash'),'GENERAL',0,'TEST_ONLY_CONTENT');
set local role anon;
select pg_temp.ok(public.read_memory_publication(current_setting('test.board')::uuid) is not null,'general board remains independent from home classification');
select pg_temp.ok(public.read_memory_publication_author(current_setting('test.board')::uuid) is null,'board author lookup cannot expose mature nickname');
reset role;
set local role authenticated;
select public.review_memory_minihome_content(current_setting('test.home')::uuid,current_setting('test.home_hash'),'GENERAL',2,'TEST_ONLY_CONTENT');
set local role anon;
select pg_temp.ok(public.read_memory_publication_author(current_setting('test.board')::uuid)->>'nickname'='Public nickname','general reviewed home restores author nickname');
reset role;
select pg_temp.ok((select count(*)=3 from private.memory_content_review_audit where target_kind='home' and target_id=current_setting('test.home')::uuid),'home audit records each successful decision');
update private.memory_publication_settings set content_policy_revision='TEST_ONLY_CONTENT_V2';
set local role anon;
select pg_temp.ok(public.read_memory_minihome(current_setting('test.home')::uuid) is null,'home old-policy approval cannot expose nickname');
reset role;
rollback;
