savepoint content_initial_review;
select pg_temp.ok(exists(select 1 from jsonb_array_elements(public.list_memory_pending_content('board')->'items') q where q->>'id'=current_setting('test.id')),'unclassified board enters first-review queue');
select set_config('test.initial_review',public.open_memory_content_review('board',current_setting('test.id')::uuid)::text,true);
select pg_temp.ok(current_setting('test.initial_review')::jsonb->>'contentRevision'='0','first review opens unclassified revision zero');
select pg_temp.ok(public.open_memory_content_review('board',current_setting('test.id')::uuid)->>'id'=current_setting('test.initial_review')::jsonb->>'id','opening same pending target reuses case');
select pg_temp.ok(public.resolve_memory_content_appeal((current_setting('test.initial_review')::jsonb->>'id')::uuid,0,0,current_setting('test.initial_review')::jsonb->>'reviewHash','GENERAL','TEST_ONLY_CONTENT')->>'status'='CLOSED','initial review uses exact package and closes request');
select pg_temp.ok(not exists(select 1 from jsonb_array_elements(public.list_memory_pending_content('board')->'items') q where q->>'id'=current_setting('test.id')),'classified current board leaves first-review queue');
reset role;
update private.memory_publication_settings set content_policy_revision='TEST_ONLY_CONTENT_V2';
set local role authenticated;
select pg_temp.ok(exists(select 1 from jsonb_array_elements(public.list_memory_pending_content('board')->'items') q where q->>'id'=current_setting('test.id')),'new policy returns board to review queue');
select set_config('test.initial_review',public.open_memory_content_review('board',current_setting('test.id')::uuid)::text,true);
reset role;
update private.memory_publications set published_snapshot=jsonb_set(published_snapshot,'{title}','"Changed during first review"') where id=current_setting('test.id')::uuid;
set local role authenticated;
select pg_temp.fails($q$select public.get_memory_content_review((current_setting('test.initial_review')::jsonb->>'id')::uuid)$q$,'PUBLICATION_CONFLICT','open first-review request cannot silently switch snapshot');
select pg_temp.fails($q$select public.resolve_memory_content_appeal((current_setting('test.initial_review')::jsonb->>'id')::uuid,0,1,current_setting('test.initial_review')::jsonb->>'reviewHash','GENERAL','TEST_ONLY_CONTENT_V2')$q$,'PUBLICATION_CONFLICT','old first-review decision cannot approve changed snapshot');
reset role;
select set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',true);
set local role authenticated;
select pg_temp.fails($q$select public.list_memory_pending_content('board')$q$,'MODERATOR_REQUIRED','ordinary account cannot list unreviewed targets');
select pg_temp.fails($q$select public.open_memory_content_review('board',current_setting('test.id')::uuid)$q$,'MODERATOR_REQUIRED','ordinary account cannot create classification case');
reset role;
rollback to content_initial_review;
