savepoint content_notice_test;
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
set local role authenticated;
select public.review_memory_publication_content(current_setting('test.id')::uuid,current_setting('test.content_hash'),'MATURE',4,'TEST_ONLY_CONTENT_V2');
reset role;
select set_config('test.content_case',(select case_id::text from private.memory_content_review_audit where target_id=current_setting('test.id')::uuid and revision=5),true);
select set_config('test.content_notice',(select id::text from private.memory_moderation_notices where case_id=current_setting('test.content_case')::uuid),true);
set local role authenticated;
select pg_temp.ok(exists(select 1 from jsonb_array_elements(public.list_memory_safety()->'items') n where n->>'id'=current_setting('test.content_notice') and n->>'action'='CONTENT_MATURE'),'owner safety inbox receives classification result');
select set_config('test.review_package',public.get_memory_content_review(current_setting('test.content_case')::uuid)::text,true);
select pg_temp.ok(current_setting('test.review_package')::jsonb->>'reviewHash'=current_setting('test.content_hash') and current_setting('test.review_package')::jsonb->>'contentRevision'='5','moderator package binds exact content hash and current revision');
select pg_temp.ok(current_setting('test.review_package')::jsonb->>'policyRevision'='TEST_ONLY_CONTENT_V2' and current_setting('test.review_package')::jsonb->>'kind'='board','moderator package includes current policy and target kind');
select pg_temp.ok(not (current_setting('test.review_package')::jsonb ? 'user_id') and position('localRef' in current_setting('test.review_package'))=0,'moderator package omits owner ID and local image reference');
reset role;
select set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',true);
set local role authenticated;
select pg_temp.ok(not exists(select 1 from jsonb_array_elements(public.list_memory_safety()->'items') n where n->>'id'=current_setting('test.content_notice')),'B cannot see owner classification notice');
select pg_temp.fails($q$select public.appeal_memory_notice(current_setting('test.content_notice')::uuid,'Review please')$q$,'NOT_FOUND','B cannot appeal owner classification');
select pg_temp.fails($q$select public.get_memory_content_review(current_setting('test.content_case')::uuid)$q$,'MODERATOR_REQUIRED','ordinary account cannot read review package');
select pg_temp.fails($q$select public.resolve_memory_content_appeal(current_setting('test.content_case')::uuid,1,5,current_setting('test.content_hash'),'GENERAL','TEST_ONLY_CONTENT_V2')$q$,'MODERATOR_REQUIRED','ordinary account cannot resolve classification appeal');
set local role anon;
select pg_temp.fails($q$select public.appeal_memory_notice(current_setting('test.content_notice')::uuid,'Review please')$q$,'permission denied','anonymous cannot appeal classification');
select pg_temp.fails($q$select public.get_memory_content_review(current_setting('test.content_case')::uuid)$q$,'permission denied','anonymous cannot read review package');
reset role;
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
set local role authenticated;
select pg_temp.ok(public.appeal_memory_notice(current_setting('test.content_notice')::uuid,'Please review this classification')->>'appealed'='true','owner can appeal using existing safety API');
select pg_temp.ok(public.appeal_memory_notice(current_setting('test.content_notice')::uuid,'duplicate retry')->>'appealed'='true','same notice appeal retry is idempotent');
select pg_temp.ok(exists(select 1 from jsonb_array_elements(public.list_memory_moderation()->'items') c where c->>'id'=current_setting('test.content_case') and c->>'status'='APPEALED'),'classification appeal reaches existing moderator queue');
select pg_temp.ok(exists(select 1 from jsonb_array_elements(public.list_memory_moderation()->'items') c where c->>'id'=current_setting('test.content_case') and c->>'reviewType'='CONTENT'),'moderator queue distinguishes classification case');
select pg_temp.fails($q$select public.review_memory_report(current_setting('test.content_case')::uuid,1,0,'RESTORE','Restore')$q$,'CONTENT_REVIEW_REQUIRED','generic restore cannot falsely resolve classification');
select pg_temp.fails($q$select public.resolve_memory_content_appeal(current_setting('test.content_case')::uuid,0,5,current_setting('test.content_hash'),'GENERAL','TEST_ONLY_CONTENT_V2')$q$,'PUBLICATION_CONFLICT','stale case cannot resolve content appeal');
select pg_temp.fails($q$select public.resolve_memory_content_appeal(current_setting('test.content_case')::uuid,1,4,current_setting('test.content_hash'),'GENERAL','TEST_ONLY_CONTENT_V2')$q$,'PUBLICATION_CONFLICT','stale content decision cannot resolve appeal');
select pg_temp.ok(public.resolve_memory_content_appeal(current_setting('test.content_case')::uuid,1,5,current_setting('test.content_hash'),'GENERAL','TEST_ONLY_CONTENT_V2')->>'status'='CLOSED','current appeal review atomically closes case');
select pg_temp.ok(public.read_memory_publication(current_setting('test.id')::uuid) is not null,'successful appeal reclassification changes actual board reader');
select pg_temp.fails($q$select public.resolve_memory_content_appeal(current_setting('test.content_case')::uuid,1,5,current_setting('test.content_hash'),'BLOCKED','TEST_ONLY_CONTENT_V2')$q$,'PUBLICATION_CONFLICT','completed appeal cannot be replayed to replace decision');
reset role;
select pg_temp.ok((select count(*)=1 from private.memory_moderation_audit where case_id=current_setting('test.content_case')::uuid and action='APPEAL'),'duplicate appeal creates one appeal audit');
select pg_temp.ok((select count(*)=1 from private.memory_moderation_audit where case_id=current_setting('test.content_case')::uuid and action='CONTENT_APPEAL_REVIEWED'),'appeal result is linked to original case audit');
select pg_temp.ok(exists(select 1 from private.memory_content_review_audit a join private.memory_moderation_notices n on n.case_id=a.case_id where a.target_id=current_setting('test.id')::uuid and a.revision=6 and n.action='CONTENT_GENERAL'),'new classification creates owner result notice');
update private.memory_publications set published_snapshot=null,state='REVOKED' where id=current_setting('test.id')::uuid;
set local role authenticated;
select pg_temp.fails($q$select public.get_memory_content_review(current_setting('test.content_case')::uuid)$q$,'NOT_FOUND','withdrawn publication cannot be recovered through moderator review package');
reset role;
delete from auth.users where id='11111111-1111-4111-8111-111111111111';
select pg_temp.ok(not exists(select 1 from private.memory_content_reviews where publication_id=current_setting('test.id')::uuid),'account deletion removes dependent current classification');
select pg_temp.ok(exists(select 1 from private.memory_content_review_audit where target_id=current_setting('test.id')::uuid),'account deletion preserves non-content decision audit');
rollback to content_notice_test;
