-- Called at the real USER_IMAGE published fixture in image-contract.sql.
-- Disposable PostgreSQL, synthetic auth/rights/derivative metadata; no hosted bytes.
begin;
reset role;
\ir content-review-candidate.sql
\ir ../../supabase/migrations/20260927042334_memory_general_postmoderation.sql
select set_config('post.board',current_setting('test.preview')::jsonb->>'id',true);
select set_config('post.asset_before',(select row_to_json(a)::text from private.memory_public_assets a where id=(current_setting('test.reservation')::jsonb->>'id')::uuid),true);
select set_config('post.source_before',(select row_to_json(a)::text from public.memory_visual_assets a where id=current_setting('test.source')::uuid),true);
select set_config('post.start',(select count(*)::text from assertions),true);
select pg_temp.ok((select general_publication_policy_revision='UNCONFIGURED' from private.memory_publication_settings),'postmoderation migration is inactive by default');
set local role anon;
select pg_temp.ok(public.read_memory_publication(current_setting('post.board')::uuid) is null,'migration does not opt old content into general publication');
reset role;
-- Even an operator reusing the old policy cannot promote an old operation replay.
update private.memory_publication_settings set content_policy_revision='TEST_ONLY',general_publication_policy_revision='TEST_ONLY';
set local role authenticated;
select public.publish_memory_publication(current_setting('post.board')::uuid,9,current_setting('test.preview')::jsonb->>'reviewHash','TEST_ONLY','eeeeeeee-eeee-4eee-8eee-000000000003');
set local role anon;
select pg_temp.ok(public.read_memory_publication(current_setting('post.board')::uuid) is null,'old operation replay does not invent general consent');
reset role;
update private.memory_publication_settings set policy_revision='TEST_ONLY_GENERAL',content_policy_revision='TEST_ONLY_GENERAL',general_publication_policy_revision='TEST_ONLY_GENERAL',minihomes_enabled=true;
set local role authenticated;
select set_config('post.preview',public.prepare_memory_publication('bbbbbbbb-bbbb-4bbb-8bbb-000000000001',10,
 '{"title":"General image board","description":"General-only consent","cards":[{"cardId":"cccccccc-cccc-4ccc-8ccc-000000000002","fields":[]}]}')::text,true);
select pg_temp.fails($q$select public.publish_memory_publication(current_setting('post.board')::uuid,11,repeat('0',64),'TEST_ONLY_GENERAL',gen_random_uuid())$q$,'CONSENT_MISMATCH','wrong preview consent is still rejected');
select pg_temp.fails($q$select public.publish_memory_publication(current_setting('post.board')::uuid,11,current_setting('post.preview')::jsonb->>'reviewHash','TEST_ONLY',gen_random_uuid())$q$,'CONSENT_MISMATCH','old policy cannot opt into general publication');
select set_config('post.operation',gen_random_uuid()::text,true);
select public.publish_memory_publication(current_setting('post.board')::uuid,11,current_setting('post.preview')::jsonb->>'reviewHash','TEST_ONLY_GENERAL',current_setting('post.operation')::uuid);
select pg_temp.ok(public.publish_memory_publication(current_setting('post.board')::uuid,11,current_setting('post.preview')::jsonb->>'reviewHash','TEST_ONLY_GENERAL',current_setting('post.operation')::uuid)->>'revision'='12','consented publish retry remains idempotent');
select pg_temp.ok(public.get_memory_publication('bbbbbbbb-bbbb-4bbb-8bbb-000000000001')->>'visible'='true','owner status reports actual general visibility');
select pg_temp.fails('update private.memory_publications set general_consent_hash=repeat(''0'',64)','permission denied','owner cannot forge server consent');
select pg_temp.fails($q$select private.publish_memory_publication_before_postmoderation(null,null,null,null,null)$q$,'permission denied','owner cannot bypass new publication wrapper');
reset role;
select pg_temp.ok(not exists(select 1 from private.memory_content_reviews),'user consent does not fabricate a moderator GENERAL decision');
select set_config('post.hash',(select encode(sha256(convert_to(published_snapshot::text,'UTF8')),'hex') from private.memory_publications where id=current_setting('post.board')::uuid),true);
set local role anon;
select pg_temp.ok(public.read_memory_publication(current_setting('post.board')::uuid)->>'title'='General image board','anonymous visitor reads unreviewed but explicitly consented general board');
set local role service_role;
select pg_temp.ok(public.resolve_memory_public_image(current_setting('post.board')::uuid,(current_setting('test.reservation')::jsonb->>'id')::uuid,'full')->>'path' like '%/full.webp','real resolver allows consented general image');
reset role;
insert into private.memory_moderators(user_id) values('11111111-1111-4111-8111-111111111111');
set local role authenticated;
select pg_temp.ok(public.list_memory_pending_content('board')->'items' @> jsonb_build_array(jsonb_build_object('id',current_setting('post.board'))),'unreported public board remains available for moderator review');
select set_config('post.case',public.open_memory_content_review('board',current_setting('post.board')::uuid)::text,true);
select set_config('post.homepreview',public.prepare_memory_minihome(0,jsonb_build_object('nickname','General public home','bio','Public introduction','entries',jsonb_build_array(jsonb_build_object('publicationId',current_setting('post.board')))))::text,true);
select set_config('post.home',current_setting('post.homepreview')::jsonb->>'id',true);
select public.publish_memory_minihome(1,current_setting('post.homepreview')::jsonb->>'reviewHash','TEST_ONLY_GENERAL',gen_random_uuid());
set local role anon;
select pg_temp.ok(jsonb_array_length(public.read_memory_minihome(current_setting('post.home')::uuid)->'entries')=1,'general home and embedded image board are visible without pre-review');
set local role authenticated;
select public.resolve_memory_content_appeal((current_setting('post.case')::jsonb->>'id')::uuid,0,0,current_setting('post.hash'),'MATURE','TEST_ONLY_GENERAL');
select pg_temp.ok(public.get_memory_publication('bbbbbbbb-bbbb-4bbb-8bbb-000000000001')->>'visible'='false','owner status does not claim blocked board is visible');
set local role anon;
select pg_temp.ok(public.read_memory_publication(current_setting('post.board')::uuid) is null,'moderator mature classification blocks anonymous board');
select pg_temp.ok(jsonb_array_length(public.read_memory_minihome(current_setting('post.home')::uuid)->'entries')=0,'moderator classification removes board from home');
set local role service_role;
select pg_temp.ok(public.resolve_memory_public_image(current_setting('post.board')::uuid,(current_setting('test.reservation')::jsonb->>'id')::uuid,'full') is null,'moderator classification closes direct full image');
select pg_temp.ok(public.resolve_memory_public_image(current_setting('post.board')::uuid,(current_setting('test.reservation')::jsonb->>'id')::uuid,'thumb') is null,'moderator classification closes direct thumbnail');
reset role;
select pg_temp.ok(exists(select 1 from private.memory_moderation_notices where action='CONTENT_MATURE' and reason like 'Adult content is not available%'),'mature notice does not promise adult verification access');
set local role authenticated;
select set_config('post.edited',public.prepare_memory_publication('bbbbbbbb-bbbb-4bbb-8bbb-000000000001',12,
 '{"title":"Changed title after restriction","description":"","cards":[{"cardId":"cccccccc-cccc-4ccc-8ccc-000000000002","fields":[]}]}')::text,true);
select pg_temp.fails($q$select public.publish_memory_publication(current_setting('post.board')::uuid,13,current_setting('post.edited')::jsonb->>'reviewHash','TEST_ONLY_GENERAL',gen_random_uuid())$q$,'PUBLICATION_RESTRICTED','changing title and republishing cannot escape mature restriction');
reset role;
update private.memory_content_reviews set policy_revision='OLD_POLICY',snapshot_hash=repeat('0',64) where publication_id=current_setting('post.board')::uuid;
set local role anon;
select pg_temp.ok(public.read_memory_publication(current_setting('post.board')::uuid) is null,'outdated negative review remains a restriction');
set local role authenticated;
select public.review_memory_publication_content(current_setting('post.board')::uuid,current_setting('post.hash'),'GENERAL',1,'TEST_ONLY_GENERAL');
select public.publish_memory_publication(current_setting('post.board')::uuid,13,current_setting('post.edited')::jsonb->>'reviewHash','TEST_ONLY_GENERAL',gen_random_uuid());
set local role anon;
select pg_temp.ok(public.read_memory_publication(current_setting('post.board')::uuid)->>'title'='Changed title after restriction','moderator re-review followed by valid consent allows update');
reset role;
select set_config('post.homehash',(select encode(sha256(convert_to(published_selection::text,'UTF8')),'hex') from private.memory_minihomes where id=current_setting('post.home')::uuid),true);
set local role authenticated;
select public.review_memory_minihome_content(current_setting('post.home')::uuid,current_setting('post.homehash'),'BLOCKED',0,'TEST_ONLY_GENERAL');
select pg_temp.ok(public.get_memory_minihome()->>'visible'='false','owner status does not claim blocked home is visible');
set local role anon;
select pg_temp.ok(public.read_memory_minihome(current_setting('post.home')::uuid) is null,'blocked home conceals nickname and introduction');
set local role authenticated;
select pg_temp.fails($q$select public.publish_memory_minihome(2,'unused','TEST_ONLY_GENERAL',gen_random_uuid())$q$,'PUBLICATION_RESTRICTED','blocked home cannot republish around restriction');
select public.review_memory_minihome_content(current_setting('post.home')::uuid,current_setting('post.homehash'),'GENERAL',1,'TEST_ONLY_GENERAL');
reset role;
update private.memory_publication_settings set content_policy_revision='TEST_ONLY_CHANGED';
set local role anon;
select pg_temp.ok(public.read_memory_publication(current_setting('post.board')::uuid) is null and public.read_memory_minihome(current_setting('post.home')::uuid) is null,'policy mismatch closes both general surfaces');
reset role;
update private.memory_publication_settings set content_policy_revision='TEST_ONLY_GENERAL',reads_enabled=false;
set local role anon;
select pg_temp.ok(public.read_memory_publication(current_setting('post.board')::uuid) is null,'existing public kill switch still closes general board');
reset role;
update private.memory_publication_settings set reads_enabled=true;
update private.memory_public_image_rights set revoked_at=now();
set local role service_role;
select pg_temp.ok(public.resolve_memory_public_image(current_setting('post.board')::uuid,(current_setting('test.reservation')::jsonb->>'id')::uuid,'full') is null,'general consent cannot bypass image rights withdrawal');
reset role;
update private.memory_public_image_rights set revoked_at=null;
set local role authenticated;
select public.revoke_memory_publication(current_setting('post.board')::uuid,14);
set local role anon;
select pg_temp.ok(public.read_memory_publication(current_setting('post.board')::uuid) is null,'owner withdrawal closes consented publication');
select pg_temp.ok(jsonb_array_length(public.read_memory_minihome(current_setting('post.home')::uuid)->'entries')=0,'owner withdrawal removes embedded board');
reset role;
select pg_temp.ok((select row_to_json(a)::text=current_setting('post.asset_before') from private.memory_public_assets a where id=(current_setting('test.reservation')::jsonb->>'id')::uuid),'moderation and consent preserve asset operation and quota');
select pg_temp.ok((select row_to_json(a)::text=current_setting('post.source_before') from public.memory_visual_assets a where id=current_setting('test.source')::uuid),'moderation and consent preserve private original metadata');
select count(*)-current_setting('post.start')::int as passed_postmoderation_assertions from assertions;
rollback;
