create temp table assertions(label text);
grant all on assertions to anon,authenticated;
create function pg_temp.ok(condition boolean,label text) returns void language plpgsql as $$
begin if condition is distinct from true then raise exception 'FAIL: %',label; end if;
insert into assertions values(label); raise notice 'PASS: %',label; end $$;
create function pg_temp.fails(statement text,expected text,label text) returns void language plpgsql as $$
begin begin execute statement; exception when others then
if position(expected in sqlerrm)>0 then perform pg_temp.ok(true,label); return; end if; raise; end;
raise exception 'Unexpected success: %',label; end $$;
\ir lifecycle-setup.sql
select public.publish_memory_publication((p->>'id')::uuid,(p->>'revision')::bigint,p->>'reviewHash',p->>'policyRevision',gen_random_uuid())
from (select public.get_memory_publication('bbbbbbbb-bbbb-4bbb-8bbb-000000000001') p) q;
select set_config('test.board',public.get_memory_publication('bbbbbbbb-bbbb-4bbb-8bbb-000000000001')->>'id',false);
select set_config('test.selection',jsonb_build_object('nickname','Public nickname','bio','Selected intro','entries',jsonb_build_array(jsonb_build_object('publicationId',current_setting('test.board'))))::text,false);
select pg_temp.fails($q$select public.prepare_memory_minihome(0,current_setting('test.selection')::jsonb)$q$,'PUBLICATION_DISABLED','minihome server flag defaults off');
reset role;
update private.memory_publication_settings set minihomes_enabled=true;
set role authenticated;
select pg_temp.ok(jsonb_array_length(public.list_memory_minihome_boards()->'boards')=1,'choices include readable public Boards only');
select pg_temp.fails('select * from private.memory_minihomes','permission denied','owner cannot read raw mini-home table');
select set_config('test.homepreview',public.prepare_memory_minihome(0,current_setting('test.selection')::jsonb)::text,false);
select set_config('test.home',current_setting('test.homepreview')::jsonb->>'id',false);
select set_config('test.originalhash',current_setting('test.homepreview')::jsonb->>'reviewHash',false);
select pg_temp.ok(public.read_memory_minihome(current_setting('test.home')::uuid) is null,'preview alone never publishes');
select pg_temp.ok(public.publish_memory_minihome(1,current_setting('test.homepreview')::jsonb->>'reviewHash','TEST_ONLY','dddddddd-dddd-4ddd-8ddd-000000000077')->>'published'='true','explicit mini-home publish');
select pg_temp.ok(public.publish_memory_minihome(1,current_setting('test.homepreview')::jsonb->>'reviewHash','TEST_ONLY','dddddddd-dddd-4ddd-8ddd-000000000077')->>'revision'='2','same operation retry is idempotent');
select pg_temp.fails($q$select public.publish_memory_minihome(1,current_setting('test.homepreview')::jsonb->>'reviewHash','WRONG','dddddddd-dddd-4ddd-8ddd-000000000077')$q$,'OPERATION_MISMATCH','same operation cannot change consent policy');
set role anon;
select pg_temp.ok(public.read_memory_publication_author(current_setting('test.board')::uuid)=jsonb_build_object('id',current_setting('test.home')::uuid,'nickname',public.read_memory_minihome(current_setting('test.home')::uuid)->>'nickname'),'board author exports only public home ID and nickname');
select pg_temp.ok(public.read_memory_minihome(current_setting('test.home')::uuid)-'id'=current_setting('test.homepreview')::jsonb->'snapshot','anonymous display equals reviewed DTO');
select pg_temp.fails('select public.get_memory_minihome()','permission denied','anonymous owner read denied');
select pg_temp.fails('select public.list_memory_minihome_boards()','permission denied','anonymous choices denied');
select pg_temp.ok(not (public.read_memory_minihome(current_setting('test.home')::uuid) ? 'user_id'),'public home omits account ID');
reset role;
select set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',false);
set role authenticated;
select pg_temp.ok(public.get_memory_minihome() is null,'B cannot recover A home');
select pg_temp.fails($q$select public.prepare_memory_minihome(0,current_setting('test.selection')::jsonb)$q$,'NOT_FOUND','B cannot exhibit A Board');
reset role;
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',false);
set role authenticated;
select set_config('test.homepreview',public.prepare_memory_minihome(2,jsonb_set(current_setting('test.selection')::jsonb,'{nickname}','"Changed name"'))::text,false);
select pg_temp.ok(public.read_memory_minihome(current_setting('test.home')::uuid)->>'nickname'='Public nickname','unpublished profile edits do not replace live name');
select public.revoke_memory_minihome(3);
select pg_temp.ok(public.publish_memory_minihome(1,current_setting('test.originalhash'),'TEST_ONLY','dddddddd-dddd-4ddd-8ddd-000000000077')->>'published'='false','successful operation replay after withdrawal stays private');
select pg_temp.ok(public.read_memory_minihome(current_setting('test.home')::uuid) is null,'home withdrawal denies visitor');
select pg_temp.ok(public.read_memory_publication(current_setting('test.board')::uuid) is not null,'home withdrawal preserves separate Board');
select pg_temp.fails($q$select public.publish_memory_minihome(3,current_setting('test.homepreview')::jsonb->>'reviewHash','TEST_ONLY',gen_random_uuid())$q$,'PUBLICATION_CONFLICT','old prepared request cannot revive withdrawn home');
select set_config('test.homepreview',public.prepare_memory_minihome(4,current_setting('test.selection')::jsonb)::text,false);
select public.publish_memory_minihome(5,current_setting('test.homepreview')::jsonb->>'reviewHash','TEST_ONLY',gen_random_uuid());
select pg_temp.ok(public.get_memory_minihome()->>'id'=current_setting('test.home'),'name/edit/republication retains stable public ID');
begin;
select public.revoke_memory_publication((p->>'id')::uuid,(p->>'revision')::bigint)
from (select public.get_memory_publication('bbbbbbbb-bbbb-4bbb-8bbb-000000000001') p) q;
set local role anon;
select pg_temp.ok(jsonb_array_length(public.read_memory_minihome(current_setting('test.home')::uuid)->'entries')=0,'withdrawing source Board removes its mini-home display');
rollback;
select pg_temp.fails($q$select public.prepare_memory_minihome(6,jsonb_set(current_setting('test.selection')::jsonb,'{entries,0,cardId}','"00000000-0000-4000-8000-000000000001"'))$q$,'PUBLICATION_RESTRICTED','unavailable representative cannot silently disappear from preview');
select set_config('test.card',(public.read_memory_publication(current_setting('test.board')::uuid)->'cards'->0->>'id'),false);
begin;
select set_config('test.representative',public.prepare_memory_minihome(6,jsonb_set(current_setting('test.selection')::jsonb,'{entries,0,cardId}',to_jsonb(current_setting('test.card'))))::text,true);
select pg_temp.ok(jsonb_array_length(current_setting('test.representative')::jsonb->'snapshot'->'entries'->0->'snapshot'->'cards')=1,'representative review contains selected public card');
reset role;
update private.memory_publication_settings set policy_revision='CHANGED';
set local role authenticated;
select pg_temp.fails($q$select public.publish_memory_minihome(7,current_setting('test.representative')::jsonb->>'reviewHash','TEST_ONLY',gen_random_uuid())$q$,'CONSENT_MISMATCH','policy change invalidates mini-home consent');
rollback;
select set_config('test.homepreview',public.prepare_memory_minihome(6,current_setting('test.selection')::jsonb)::text,false);
reset role;
update private.memory_publications set published_snapshot=jsonb_set(published_snapshot,'{title}','"Board explicit update"') where id=current_setting('test.board')::uuid;
set role authenticated;
select pg_temp.fails($q$select public.publish_memory_minihome(7,current_setting('test.homepreview')::jsonb->>'reviewHash','TEST_ONLY',gen_random_uuid())$q$,'PREVIEW_CHANGED','Board update after home preview requires new review');
select public.retire_memory_card_publications('cccccccc-cccc-4ccc-8ccc-000000000001');
set role anon;
select pg_temp.ok(jsonb_array_length(public.read_memory_minihome(current_setting('test.home')::uuid)->'entries')=0,'card-wide retirement removes mini-home display');
reset role;
update private.memory_publication_accounts set hidden=true where user_id='11111111-1111-4111-8111-111111111111';
set role anon;
select pg_temp.ok(public.read_memory_minihome(current_setting('test.home')::uuid) is null,'hidden account closes mini-home');
select pg_temp.ok(public.read_memory_publication_author(current_setting('test.board')::uuid) is null,'hidden author link omitted');
reset role;
update private.memory_publication_settings set minihomes_enabled=false;
set role anon;
select pg_temp.ok(public.read_memory_minihome(current_setting('test.home')::uuid) is null,'mini-home kill switch closes read');
reset role;
select count(*) as minihome_assertions from assertions;
