\set ON_ERROR_STOP on
create function pg_temp.ok(condition boolean,label text) returns void language plpgsql as $$
begin if condition is distinct from true then raise exception 'FAIL: %',label; end if; raise notice 'PASS: %',label; end $$;
create function pg_temp.fails(statement text,expected text,label text) returns void language plpgsql as $$
begin begin execute statement; exception when others then
if position(expected in sqlerrm)>0 then perform pg_temp.ok(true,label); return; end if; raise; end;
raise exception 'Unexpected success: %',label; end $$;
insert into auth.users(id) values('33333333-3333-4333-8333-333333333333') on conflict do nothing;
insert into private.memory_moderators(user_id) values('33333333-3333-4333-8333-333333333333');
select set_config('test.home',(select id::text from private.memory_minihomes where user_id='11111111-1111-4111-8111-111111111111'),false);
select set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',false);
set role authenticated;
select pg_temp.fails($q$select public.submit_memory_report('home',current_setting('test.home')::uuid,'SAFETY','aaaaaaaa-aaaa-4aaa-8aaa-000000000001','')$q$,'PUBLICATION_DISABLED','reports default off');
select pg_temp.fails('select public.list_memory_moderation()','MODERATOR_REQUIRED','normal account cannot moderate');
select pg_temp.fails('select * from private.memory_reports','permission denied','report table is not directly readable');
select pg_temp.fails($q$insert into private.memory_moderators values(auth.uid(),true)$q$,'permission denied','client cannot grant itself moderator');
reset role;
update private.memory_publication_settings set reports_enabled=true,report_daily_limit=2;
set role authenticated;
select set_config('test.report',public.submit_memory_report('home',current_setting('test.home')::uuid,'SAFETY','aaaaaaaa-aaaa-4aaa-8aaa-000000000001','Review this public home')->>'id',false);
select pg_temp.ok(public.submit_memory_report('home',current_setting('test.home')::uuid,'SAFETY','aaaaaaaa-aaaa-4aaa-8aaa-000000000001','Review this public home')->>'id'=current_setting('test.report'),'blocked relationship does not suppress report; retry same receipt');
select pg_temp.ok(public.submit_memory_report('home',current_setting('test.home')::uuid,'SAFETY',gen_random_uuid(),'duplicate')->>'id'=current_setting('test.report'),'open duplicate converges to same case');
select pg_temp.fails($q$select public.submit_memory_report('home',current_setting('test.home')::uuid,'RIGHTS','aaaaaaaa-aaaa-4aaa-8aaa-000000000001','')$q$,'OPERATION_MISMATCH','operation cannot change report payload');
select set_config('test.report2',public.submit_memory_report('home',current_setting('test.home')::uuid,'RIGHTS',gen_random_uuid(),'Review rights')->>'id',false);
select pg_temp.fails($q$select public.submit_memory_report('home',current_setting('test.home')::uuid,'SPAM',gen_random_uuid(),'')$q$,'RATE_LIMITED','daily report quota enforced');
select pg_temp.ok(jsonb_array_length(public.list_memory_safety()->'items')=2,'reporter sees own receipts');
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',false);
select pg_temp.ok(jsonb_array_length(public.list_memory_safety()->'items')=0,'reported owner cannot see reporter receipts');
select set_config('request.jwt.claim.sub','33333333-3333-4333-8333-333333333333',false);
select pg_temp.ok(jsonb_array_length(public.list_memory_moderation()->'items')=2,'allowlisted moderator sees queue');
select pg_temp.ok(public.review_memory_report(current_setting('test.report')::uuid,0,0,'HIDE','Public safety review')->>'revision'='1','moderator hide succeeds');
select pg_temp.ok(public.read_memory_minihome(current_setting('test.home')::uuid) is null,'moderator hide denies public reader');
begin;
select public.review_memory_report(current_setting('test.report')::uuid,1,1,'RESTORE','Visibility restored after review');
select pg_temp.ok(public.read_memory_minihome(current_setting('test.home')::uuid) is not null,'restore shows still-consented home');
rollback;
select pg_temp.fails($q$select public.review_memory_report(current_setting('test.report')::uuid,0,0,'RESTORE','stale')$q$,'PUBLICATION_CONFLICT','stale case action rejected');
select pg_temp.fails($q$select public.review_memory_report(current_setting('test.report2')::uuid,0,0,'RESTORE','stale target')$q$,'PUBLICATION_CONFLICT','different case cannot overwrite newer target review');
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',false);
select set_config('test.notice',public.list_memory_safety()->'items'->0->>'id',false);
select pg_temp.ok(public.list_memory_safety()->'items'->0->>'reason'='Public safety review','owner receives action reason');
select pg_temp.ok(not (public.list_memory_safety()->'items'->0 ? 'reporter'),'notice conceals reporter identity');
select pg_temp.ok(public.appeal_memory_notice(current_setting('test.notice')::uuid,'Please review again')->>'appealed'='true','owner appeal accepted');
select pg_temp.ok(public.appeal_memory_notice(current_setting('test.notice')::uuid,'Please review again')->>'appealed'='true','appeal retry idempotent');
select public.revoke_memory_minihome((public.get_memory_minihome()->>'revision')::bigint);
select set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',false);
select pg_temp.fails($q$select public.appeal_memory_notice(current_setting('test.notice')::uuid,'Other user')$q$,'NOT_FOUND','B cannot appeal A notice');
select set_config('request.jwt.claim.sub','33333333-3333-4333-8333-333333333333',false);
select pg_temp.ok(public.review_memory_report(current_setting('test.report')::uuid,2,1,'RESTORE','Review resolved')->>'targetRevision'='2','appeal review can remove moderation hide');
select pg_temp.ok(public.read_memory_minihome(current_setting('test.home')::uuid) is null,'restore does not republish owner withdrawal');
select public.review_memory_report(current_setting('test.report')::uuid,3,2,'RESTRICT_ACCOUNT','Public writes restricted pending review');
select public.review_memory_report(current_setting('test.report2')::uuid,0,3,'RESTRICT_ACCOUNT','Separate case restriction');
select public.review_memory_report(current_setting('test.report')::uuid,4,4,'RELEASE_ACCOUNT','First restriction released');
reset role;
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',false);
select pg_temp.fails('select private.require_publication_writer()','PUBLICATION_RESTRICTED','one release does not lift another active case sanction');
select pg_temp.fails($q$update private.memory_public_assets set state='READY' where id=(select id from private.memory_public_assets where user_id=auth.uid() limit 1)$q$,'PUBLICATION_RESTRICTED','restricted account cannot finalize prepared public image');
set role authenticated;
select pg_temp.fails($q$select public.prepare_memory_minihome(0,'{}')$q$,'PUBLICATION_RESTRICTED','actual publication RPC enforces case restriction');
select pg_temp.ok(public.revoke_memory_minihome((public.get_memory_minihome()->>'revision')::bigint)->>'published'='false','restricted owner can still withdraw');
select set_config('request.jwt.claim.sub','33333333-3333-4333-8333-333333333333',false);
select public.review_memory_report(current_setting('test.report2')::uuid,1,5,'RELEASE_ACCOUNT','Second restriction released');
select pg_temp.ok(jsonb_array_length(public.read_memory_moderation_audit(current_setting('test.report')::uuid))=5,'immutable audit includes review appeal and releases');
reset role;
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',false);
select pg_temp.ok(private.require_publication_writer()=auth.uid(),'all case releases restore writes without altering legacy flags');
set role anon;
select pg_temp.fails('select public.list_memory_safety()','permission denied','anonymous inbox denied');
select pg_temp.fails('select public.list_memory_moderation()','permission denied','anonymous moderation denied');
reset role;
begin;
delete from auth.users where id='22222222-2222-4222-8222-222222222222';
select pg_temp.ok(exists(select 1 from private.memory_reports where id=current_setting('test.report')::uuid and reporter is null),'reporter deletion preserves audit without blocking account deletion');
rollback;
begin;
update private.memory_publication_settings set report_daily_limit=3;
select set_config('test.board',(select id::text from private.memory_publications where board_id='bbbbbbbb-bbbb-4bbb-8bbb-000000000001'),false);
select set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',false);
set role authenticated;
select set_config('test.boardreport',public.submit_memory_report('board',current_setting('test.board')::uuid,'SAFETY',gen_random_uuid(),'Public Board review')->>'id',false);
select set_config('request.jwt.claim.sub','33333333-3333-4333-8333-333333333333',false);
select public.review_memory_report(current_setting('test.boardreport')::uuid,0,0,'HIDE','Board temporarily hidden');
select pg_temp.ok(public.read_memory_publication(current_setting('test.board')::uuid) is null,'Board hide closes shared page and image reader dependency');
select public.review_memory_report(current_setting('test.boardreport')::uuid,1,1,'RESTORE','Board review resolved');
select pg_temp.ok(public.read_memory_publication(current_setting('test.board')::uuid) is not null,'Board restore preserves existing consent');
rollback;
