\set ON_ERROR_STOP on
\timing on
create function pg_temp.ok(condition boolean,label text) returns void language plpgsql as $$
begin if condition is distinct from true then raise exception 'FAIL: %',label; end if; raise notice 'PASS: %',label; end $$;
create function pg_temp.fails(statement text,expected text,label text) returns void language plpgsql as $$
begin begin execute statement; exception when others then
if position(expected in sqlerrm)>0 then perform pg_temp.ok(true,label); return; end if; raise; end;
raise exception 'Unexpected success: %',label; end $$;
select pg_temp.ok(not exists(select 1 from private.memory_resource_policies where enabled or paused),'new budgets default inactive until approval');
select pg_temp.ok((select count(*)=1 from public.user_follows),'legacy relationship rows preserved');
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',false);
set role authenticated;
select public.register_user_device('dddddddd-dddd-4ddd-8ddd-000000000099','eeeeeeee-eeee-4eee-8eee-000000000099','WEB','budget-test');
select pg_temp.fails('select * from private.memory_resource_usage','permission denied','client cannot read other usage');
select pg_temp.fails('update private.memory_resource_policies set enabled=false','permission denied','client cannot disable budget');
select pg_temp.fails('select * from public.user_follows','permission denied','legacy relationship graph access closed');
select pg_temp.fails($q$insert into public.user_showcase_public values(auth.uid(),'{}')$q$,'permission denied','legacy showcase write bypass closed');
select pg_temp.fails($q$insert into public.memory_boards(id,user_id,title,client_updated_at) values(gen_random_uuid(),auth.uid(),'bypass',now())$q$,'permission denied','direct REST-equivalent write cannot bypass RPC');
reset role;
update private.memory_resource_policies set enabled=true,daily_limit=1,live_limit=100 where scope='SYNC_MEMORY_BOARDS';
set role authenticated;
select set_config('test.boardop','aaaaaaaa-aaaa-4aaa-8aaa-000000000099',false);
select set_config('test.boardid','bbbbbbbb-bbbb-4bbb-8bbb-000000000099',false);
select pg_temp.ok(public.apply_board_mutation(current_setting('test.boardop')::uuid,'dddddddd-dddd-4ddd-8ddd-000000000099','MEMORY_BOARD',current_setting('test.boardid')::uuid,'UPSERT',0,repeat('a',64),'{"title":"Budget fixture","description":""}')->>'status'='APPLIED','actual sync RPC consumes server work budget');
select pg_temp.ok(public.apply_board_mutation(current_setting('test.boardop')::uuid,'dddddddd-dddd-4ddd-8ddd-000000000099','MEMORY_BOARD',current_setting('test.boardid')::uuid,'UPSERT',0,repeat('a',64),'{"title":"Budget fixture","description":""}')->>'status'='APPLIED','same operation replay succeeds at exhausted budget');
select pg_temp.fails($q$select public.apply_board_mutation(gen_random_uuid(),'dddddddd-dddd-4ddd-8ddd-000000000099','MEMORY_BOARD',current_setting('test.boardid')::uuid,'UPSERT',1,repeat('b',64),'{"title":"Over budget","description":""}')$q$,'SYNC_RATE_LIMITED','second successful-work request rejected');
select pg_temp.ok((select title='Budget fixture' from public.memory_boards where id=current_setting('test.boardid')::uuid),'overage rolls back source and version');
select pg_temp.ok((select count(*)=1 from jsonb_array_elements(public.get_memory_resource_usage()) q where q->>'scope'='SYNC_MEMORY_BOARDS' and q->>'used'='1'),'owner usage contains committed changes only');
reset role;
update private.memory_resource_policies set paused=true where scope='SYNC_MEMORY_BOARDS';
set role authenticated;
select pg_temp.ok(public.apply_board_mutation(gen_random_uuid(),'dddddddd-dddd-4ddd-8ddd-000000000099','MEMORY_BOARD',current_setting('test.boardid')::uuid,'DELETE',1,repeat('c',64),'{}')->>'status'='APPLIED','delete succeeds while paused and over budget');
select pg_temp.fails($q$select public.apply_board_mutation(gen_random_uuid(),'dddddddd-dddd-4ddd-8ddd-000000000099','MEMORY_BOARD',gen_random_uuid(),'UPSERT',0,repeat('d',64),'{"title":"Paused","description":""}')$q$,'SYNC_PAUSED','paused creation denied');
reset role;
update private.memory_resource_policies set paused=false where scope='SYNC_MEMORY_BOARDS';
insert into private.memory_resource_overrides values('11111111-1111-4111-8111-111111111111','SYNC_MEMORY_BOARDS',10,0,now()+interval '1 hour','LOCAL ONLY capacity test');
set role authenticated;
select pg_temp.fails($q$select public.apply_board_mutation(gen_random_uuid(),'dddddddd-dddd-4ddd-8ddd-000000000099','MEMORY_BOARD',gen_random_uuid(),'UPSERT',0,repeat('e',64),'{"title":"Capacity","description":""}')$q$,'SYNC_QUOTA_EXCEEDED','live row capacity enforced');
reset role;
update private.memory_resource_overrides set live_limit=100;
set role authenticated;
select pg_temp.ok(public.apply_board_mutation(gen_random_uuid(),'dddddddd-dddd-4ddd-8ddd-000000000099','MEMORY_BOARD','bbbbbbbb-bbbb-4bbb-8bbb-000000000098','UPSERT',0,repeat('f',64),'{"title":"Override","description":""}')->>'status'='APPLIED','active override allows recovery');
reset role;
update private.memory_resource_overrides set expires_at=now()-interval '1 second';
set role authenticated;
select pg_temp.fails($q$select public.apply_board_mutation(gen_random_uuid(),'dddddddd-dddd-4ddd-8ddd-000000000099','MEMORY_BOARD',gen_random_uuid(),'UPSERT',0,repeat('e',64),'{"title":"Expired","description":""}')$q$,'SYNC_RATE_LIMITED','expired override restores ordinary limit');
select set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',false);
select pg_temp.ok(not exists(select 1 from jsonb_array_elements(public.get_memory_resource_usage()) q where (q->>'used')::bigint>0),'B does not inherit A usage');
reset role;
update private.memory_resource_policies set enabled=false;
\ir lifecycle-setup.sql
reset role;
update private.memory_resource_policies set enabled=true,daily_limit=1 where scope in ('PUBLIC_PREPARE','PUBLIC_PUBLISH');
set role authenticated;
select set_config('test.preview',public.prepare_memory_publication('bbbbbbbb-bbbb-4bbb-8bbb-000000000001',(public.get_memory_publication('bbbbbbbb-bbbb-4bbb-8bbb-000000000001')->>'revision')::bigint,'{"title":"Quota public","description":"","cards":[{"cardId":"cccccccc-cccc-4ccc-8ccc-000000000001","fields":[]}]}')::text,false);
select pg_temp.fails($q$select public.prepare_memory_publication('bbbbbbbb-bbbb-4bbb-8bbb-000000000001',(current_setting('test.preview')::jsonb->>'revision')::bigint,'{"title":"Quota public","description":"","cards":[{"cardId":"cccccccc-cccc-4ccc-8ccc-000000000001","fields":[]}]}')$q$,'RATE_LIMITED','identical new preparation still consumes revision work');
select set_config('test.publishop',gen_random_uuid()::text,false);
select public.publish_memory_publication((p->>'id')::uuid,(p->>'revision')::bigint,p->>'reviewHash',p->>'policyRevision',current_setting('test.publishop')::uuid) from (select current_setting('test.preview')::jsonb p) q;
select pg_temp.ok(public.publish_memory_publication((p->>'id')::uuid,(p->>'revision')::bigint,p->>'reviewHash',p->>'policyRevision',current_setting('test.publishop')::uuid)->>'state'='PUBLISHED','publish acknowledgement retry does not double charge') from (select current_setting('test.preview')::jsonb p) q;
reset role;
update private.memory_resource_policies set paused=true where scope in ('PUBLIC_PREPARE','PUBLIC_PUBLISH');
set role authenticated;
select pg_temp.ok(public.revoke_memory_publication((p->>'id')::uuid,(p->>'revision')::bigint)->>'state'='REVOKED','public withdrawal exempt from budget pause') from (select public.get_memory_publication('bbbbbbbb-bbbb-4bbb-8bbb-000000000001') p) q;
select public.retire_memory_card_publications(gen_random_uuid());
select pg_temp.ok(true,'unknown-source delete fence remains available for delayed sync safety');
select pg_temp.fails('select public.authorize_memory_image_delivery(1)','permission denied','client cannot consume or impersonate global delivery budget');
reset role;
update private.memory_resource_policies set enabled=true,daily_limit=1 where scope='IMAGE_ATTEMPT';
set role authenticated;
select public.authorize_memory_image_attempt();
select pg_temp.fails('select public.authorize_memory_image_attempt()','RATE_LIMITED','image conversion attempts have separate authenticated budget');
reset role;
update private.memory_relationships set following=false,blocked=false;
update private.memory_resource_policies set enabled=true,daily_limit=1,live_limit=1 where scope='FOLLOW_WRITE';
select set_config('test.homeb',(select id::text from private.memory_minihomes where user_id='22222222-2222-4222-8222-222222222222'),false);
set role authenticated;
select public.set_memory_relationship(current_setting('test.homeb')::uuid,'follow');
select pg_temp.ok(public.set_memory_relationship(current_setting('test.homeb')::uuid,'follow')->>'following'='true','duplicate follow is not double charged');
select public.set_memory_relationship(current_setting('test.homeb')::uuid,'unfollow');
select pg_temp.fails($q$select public.set_memory_relationship(current_setting('test.homeb')::uuid,'follow')$q$,'RATE_LIMITED','new follow consumes relationship budget');
select pg_temp.ok(public.set_memory_relationship(current_setting('test.homeb')::uuid,'block')->>'blocked'='true','safety blocking remains available over quota');
reset role;
update private.memory_resource_policies set enabled=true,daily_limit=1 where scope='IMAGE_DELIVERY';
update private.memory_resource_policies set enabled=true,daily_limit=2097152 where scope='IMAGE_DELIVERY_BYTES';
set role service_role;
select public.authorize_memory_image_delivery(2097152);
select pg_temp.fails('select public.authorize_memory_image_delivery(1)','RATE_LIMITED','global image request budget enforced');
reset role;
update private.memory_resource_policies set daily_limit=2 where scope='IMAGE_DELIVERY';
set role service_role;
select pg_temp.fails('select public.authorize_memory_image_delivery(1)','RATE_LIMITED','global reserved byte budget enforced');
reset role;
select pg_temp.ok((select used=1 from private.memory_resource_usage where scope='IMAGE_DELIVERY'),'failed byte reservation rolls back request counter atomically');
update private.memory_resource_usage set window_day=(now() at time zone 'UTC')::date-1 where scope like 'IMAGE_DELIVERY%';
set role service_role;
select public.authorize_memory_image_delivery(2097152);
reset role;
select pg_temp.ok((select used=1 from private.memory_resource_usage where scope='IMAGE_DELIVERY'),'new UTC day resets existing counter row');
select set_config('request.jwt.claim.sub','33333333-3333-4333-8333-333333333333',false);
set role authenticated;
select pg_temp.ok(public.inspect_memory_resource_costs()->>'deleteFences' is not null,'moderator receives aggregate cost and fence counts');
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',false);
select pg_temp.fails('select public.inspect_memory_resource_costs()','MODERATOR_REQUIRED','ordinary user cannot inspect global costs');
set role anon;
select pg_temp.fails('select * from public.user_profiles','permission denied','legacy anonymous profile access closed');
select pg_temp.fails('select public.get_memory_resource_usage()','permission denied','anonymous usage inspection denied');
