-- Disposable synthetic fixture only; real PostgreSQL functions and ACLs, no hosted Storage.
begin;
reset role;
\ir content-review-candidate.sql
\ir ../../supabase/migrations/20260927042334_memory_general_postmoderation.sql
\ir ../../supabase/migrations/20260927044435_memory_self_declared_image_rights.sql
select set_config('decl.start',(select count(*)::text from assertions),true);
select set_config('decl.source_before',(select row_to_json(a)::text from public.memory_visual_assets a where id=current_setting('test.source')::uuid),true);
create function pg_temp.declare_image(op uuid default gen_random_uuid(), hash text default repeat('b',64), rep uuid default null, rep_hash text default null) returns jsonb language sql as $$
 select public.reserve_memory_declared_public_asset(current_setting('test.source')::uuid,1,op,'TEST_DECLARED',hash,rep,rep_hash)
$$;
set local role authenticated;
select pg_temp.fails('select pg_temp.declare_image()','CONSENT_MISMATCH','declarations are disabled by default');
reset role;
select pg_temp.ok((select bool_and(evidence_kind='TRUSTED' and approved_at is not null) from private.memory_public_image_rights),'existing rights remain trusted approvals');
delete from private.memory_public_image_rights where asset_id=current_setting('test.source')::uuid;
update private.memory_publication_settings set policy_revision='TEST_DECLARED',general_publication_policy_revision='TEST_DECLARED',content_policy_revision='TEST_DECLARED',asset_limit=20,asset_bytes_limit=100000000;
set local role anon;
select pg_temp.fails('select pg_temp.declare_image()','permission denied','anonymous cannot declare image rights');
set local role authenticated;
select pg_temp.fails($q$select pg_temp.declare_image(gen_random_uuid(),repeat('f',64))$q$,'SOURCE_IMAGE_MISMATCH','wrong original bytes cannot create declaration');
reset role;
select pg_temp.ok(not exists(select 1 from private.memory_public_image_rights where asset_id=current_setting('test.source')::uuid),'failed hash leaves no declaration');
update private.memory_publication_settings set asset_limit=0;
set local role authenticated;
select pg_temp.fails('select pg_temp.declare_image()','IMAGE_QUOTA_EXCEEDED','quota failure rejects declared reservation');
reset role;
select pg_temp.ok(not exists(select 1 from private.memory_public_image_rights where asset_id=current_setting('test.source')::uuid),'quota failure rolls back declaration');
update private.memory_publication_settings set asset_limit=20;
insert into public.user_profiles(user_id,display_name) values('22222222-2222-4222-8222-222222222222','Synthetic B') on conflict do nothing;
set local role authenticated;
select set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',true);
select pg_temp.fails('select pg_temp.declare_image()','PUBLIC_VISUAL_NOT_READY','B cannot declare rights on A image');
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
select set_config('decl.operation',gen_random_uuid()::text,true);
select set_config('decl.asset',pg_temp.declare_image(current_setting('decl.operation')::uuid)::text,true);
select pg_temp.fails($q$select pg_temp.declare_image(current_setting('decl.operation')::uuid)$q$,'ASSET_OPERATION_UNAVAILABLE','pending retry retains operation and reservation');
reset role;
select pg_temp.ok((select evidence_kind='SELF_DECLARED' and approved_at is null and declared_at is not null and declaration_source_hash=repeat('b',64) and declaration_policy='TEST_DECLARED' from private.memory_public_image_rights where asset_id=current_setting('test.source')::uuid),'own declaration is distinct from trusted approval and bound to exact source');
select pg_temp.ok(not exists(select 1 from private.memory_content_reviews),'image declaration creates no moderator classification');
savepoint trusted_preserved;
update private.memory_public_image_rights set evidence_kind='TRUSTED',approved_at=now(),evidence_ref='SYNTHETIC_LICENSE',image_type='LICENSED_IMAGE' where asset_id=current_setting('test.source')::uuid;
select set_config('decl.trusted',(select row_to_json(r)::text from private.memory_public_image_rights r where asset_id=current_setting('test.source')::uuid),true);
set local role authenticated;
select pg_temp.declare_image();
reset role;
select pg_temp.ok((select row_to_json(r)::text=current_setting('decl.trusted') from private.memory_public_image_rights r where asset_id=current_setting('test.source')::uuid),'declaration never replaces trusted license evidence');
rollback to trusted_preserved;
update private.memory_publication_settings set policy_revision='CHANGED_POLICY';
set local role authenticated;
select pg_temp.fails('select pg_temp.declare_image()','CONSENT_MISMATCH','policy change requires fresh confirmation');
set local role service_role;
select pg_temp.fails($q$select public.complete_memory_public_asset((current_setting('decl.asset')::jsonb->>'id')::uuid,repeat('c',64),repeat('d',64),100,50,10,10)$q$,'IMAGE_RIGHTS_REQUIRED','policy change while processing denies completion');
reset role;
select pg_temp.ok((select state='PREPARING' and reserved_bytes=4194304 from private.memory_public_assets where id=(current_setting('decl.asset')::jsonb->>'id')::uuid),'failed completion retains pending reservation for cleanup or recovery');
update private.memory_publication_settings set policy_revision='TEST_DECLARED';
set local role service_role;
select public.complete_memory_public_asset((current_setting('decl.asset')::jsonb->>'id')::uuid,repeat('c',64),repeat('d',64),100,50,10,10);
set local role authenticated;
select pg_temp.ok(pg_temp.declare_image(current_setting('decl.operation')::uuid)->>'state'='READY','completed declaration retry recovers same operation');
select pg_temp.ok(public.resolve_memory_image_preview((current_setting('decl.asset')::jsonb->>'id')::uuid,'full') is not null,'declared original has an owner preview');
select set_config('decl.preview',public.prepare_memory_publication('bbbbbbbb-bbbb-4bbb-8bbb-000000000001',10,
 '{"title":"Own creation","description":"","cards":[{"cardId":"cccccccc-cccc-4ccc-8ccc-000000000002","fields":[]}]}')::text,true);
select public.publish_memory_publication((current_setting('decl.preview')::jsonb->>'id')::uuid,11,current_setting('decl.preview')::jsonb->>'reviewHash','TEST_DECLARED',gen_random_uuid());
set local role anon;
select pg_temp.ok(public.read_memory_publication((current_setting('decl.preview')::jsonb->>'id')::uuid)->>'title'='Own creation','self-declared general image publishes without trusted preapproval');
set local role service_role;
select pg_temp.ok(public.resolve_memory_public_image((current_setting('decl.preview')::jsonb->>'id')::uuid,(current_setting('decl.asset')::jsonb->>'id')::uuid,'full') is not null,'anonymous delivery resolver permits exact declared image');
reset role;
insert into private.memory_private_media(id,owner_id,asset_id,source_version,operation_id,policy_revision,pipeline,input_hash,main_hash,thumb_hash,main_bytes,thumb_bytes,width,height,state) values
 ('dddddddd-dddd-4ddd-8ddd-000000000007','11111111-1111-4111-8111-111111111111',current_setting('test.source')::uuid,1,gen_random_uuid(),'PRIVATE_TEST','private-webp-v1',repeat('b',64),repeat('e',64),repeat('f',64),100,50,10,10,'READY');
set local role authenticated;
select pg_temp.fails($q$select pg_temp.declare_image(gen_random_uuid(),null,'dddddddd-dddd-4ddd-8ddd-000000000007',repeat('a',64))$q$,'PUBLIC_VISUAL_NOT_READY','different optimized bytes cannot reuse a source declaration');
select set_config('decl.rep',pg_temp.declare_image(gen_random_uuid(),null,'dddddddd-dddd-4ddd-8ddd-000000000007',repeat('e',64))::text,true);
reset role;
select pg_temp.ok((select evidence_kind='SELF_DECLARED' and approved_at is null and representation_hash=repeat('e',64) from private.memory_representation_public_rights where representation_id='dddddddd-dddd-4ddd-8ddd-000000000007'),'private-copy declaration records exact representation separately');
set local role service_role;
select public.complete_memory_public_asset((current_setting('decl.rep')::jsonb->>'id')::uuid,repeat('c',64),repeat('d',64),100,50,10,10);
set local role authenticated;
select pg_temp.ok(public.resolve_memory_image_preview((current_setting('decl.rep')::jsonb->>'id')::uuid,'full') is not null,'declared optimized copy can be previewed');
reset role;
update private.memory_representation_public_rights set revoked_at=now() where representation_id='dddddddd-dddd-4ddd-8ddd-000000000007';
set local role authenticated;
select pg_temp.fails($q$select pg_temp.declare_image(gen_random_uuid(),null,'dddddddd-dddd-4ddd-8ddd-000000000007',repeat('e',64))$q$,'IMAGE_RIGHTS_REQUIRED','self declaration cannot revive revoked representation');
select pg_temp.ok(public.resolve_memory_image_preview((current_setting('decl.rep')::jsonb->>'id')::uuid,'full') is null,'representation revocation closes preview');
reset role;
update private.memory_publication_settings set general_publication_policy_revision='UNCONFIGURED';
set local role authenticated;
select pg_temp.ok(public.resolve_memory_image_preview((current_setting('decl.asset')::jsonb->>'id')::uuid,'full') is null,'policy rollback closes self-declared original');
reset role;
update private.memory_publication_settings set general_publication_policy_revision='TEST_DECLARED';
update private.memory_public_image_rights set revoked_at=now() where asset_id=current_setting('test.source')::uuid;
set local role authenticated;
select pg_temp.fails('select pg_temp.declare_image()','IMAGE_RIGHTS_REQUIRED','self declaration cannot revive revoked source');
set local role service_role;
select pg_temp.ok(public.resolve_memory_public_image((current_setting('decl.preview')::jsonb->>'id')::uuid,(current_setting('decl.asset')::jsonb->>'id')::uuid,'full') is null,'source withdrawal closes already published image');
reset role;
select pg_temp.ok((select row_to_json(a)::text=current_setting('decl.source_before') from public.memory_visual_assets a where id=current_setting('test.source')::uuid),'declaration never changes private source metadata or bytes');
select pg_temp.ok(not has_function_privilege('anon','public.reserve_memory_declared_public_asset(uuid,bigint,uuid,text,text,uuid,text)','execute') and not has_table_privilege('authenticated','private.memory_public_image_rights','insert'),'no anonymous declaration or direct rights-table writes');
select count(*)-current_setting('decl.start')::int as passed_declaration_assertions from assertions;
rollback;
