create function pg_temp.ok(value boolean,label text) returns void language plpgsql as $$begin if value is distinct from true then raise exception 'FAIL: %',label;end if;raise notice 'PASS: %',label;end $$;
select set_config('test.viewer.board',(select id::text from private.memory_publications where board_id='55555555-5555-4555-8555-555555555550'),false);
select set_config('test.viewer.home',(select id::text from private.memory_minihomes where user_id='77777777-7777-4777-8777-777777777777'),false);
select set_config('request.jwt.claim.sub','',false);
set role anon;
select pg_temp.ok(public.read_memory_publication(current_setting('test.viewer.board')::uuid) is not null,'GENERAL remains anonymously readable');
reset role;
update private.memory_content_reviews set rating='MATURE' where publication_id=current_setting('test.viewer.board')::uuid;
update private.memory_minihomes set published_selection=jsonb_build_object('nickname','Synthetic mature home','bio','','entries',jsonb_build_array(jsonb_build_object('publicationId',current_setting('test.viewer.board')))) where id=current_setting('test.viewer.home')::uuid;
insert into private.memory_home_content_reviews(home_id,snapshot_hash,rating,reviewed_by,policy_revision)
select id,encode(sha256(convert_to(published_selection::text,'UTF8')),'hex'),'MATURE',user_id,'LOCAL_CONTENT' from private.memory_minihomes where id=current_setting('test.viewer.home')::uuid;
set role anon;
select pg_temp.ok(public.read_memory_publication(current_setting('test.viewer.board')::uuid) is null and public.read_memory_minihome(current_setting('test.viewer.home')::uuid) is null,'anonymous cannot read MATURE board or home');
reset role;
insert into auth.sessions(id,user_id) values('33333333-3333-4333-8333-333333333333','88888888-8888-4888-8888-888888888888');
select set_config('request.jwt.claim.sub','88888888-8888-4888-8888-888888888888',false);
select set_config('request.jwt.claims',jsonb_build_object('sub','88888888-8888-4888-8888-888888888888','session_id','33333333-3333-4333-8333-333333333333','role','authenticated','is_anonymous',false,'exp',floor(extract(epoch from clock_timestamp()+interval '1 hour')))::text,false);
set role authenticated;
select pg_temp.ok(public.read_memory_publication(current_setting('test.viewer.board')::uuid) is null,'signed-in viewer has no implicit mature grant');
reset role;
insert into private.memory_eligibility_evidence values('88888888-8888-4888-8888-888888888888','MATURE_VIEW','LOCAL_MATURE','GRANTED',gen_random_uuid(),clock_timestamp()+interval '1 hour',1);
set role authenticated;
select pg_temp.ok(public.read_memory_publication(current_setting('test.viewer.board')::uuid) is null,'MATURE policy remains default off despite synthetic grant');
reset role;
update private.memory_eligibility_policies set enabled=true,revision='LOCAL_MATURE' where purpose='MATURE_VIEW';
set role authenticated;
select pg_temp.ok(public.read_memory_publication(current_setting('test.viewer.board')::uuid) is not null and jsonb_array_length(public.read_memory_minihome(current_setting('test.viewer.home')::uuid)->'entries')=1,'eligible viewer reads reviewed board and nested home');
reset role;
update private.memory_eligibility_evidence set state='REVOKED' where purpose='MATURE_VIEW';
set role authenticated;
select pg_temp.ok(public.read_memory_publication(current_setting('test.viewer.board')::uuid) is null and public.read_memory_minihome(current_setting('test.viewer.home')::uuid) is null,'revocation closes both metadata surfaces');
reset role;
update private.memory_eligibility_evidence set state='GRANTED',expires_at=clock_timestamp()-interval '1 second' where purpose='MATURE_VIEW';
set role authenticated;
select pg_temp.ok(public.read_memory_publication(current_setting('test.viewer.board')::uuid) is null,'expired mature evidence denied');
reset role;
update private.memory_eligibility_evidence set expires_at=clock_timestamp()+interval '1 hour' where purpose='MATURE_VIEW';
update private.memory_eligibility_policies set revision='LOCAL_CHANGED' where purpose='MATURE_VIEW';
set role authenticated;
select pg_temp.ok(public.read_memory_publication(current_setting('test.viewer.board')::uuid) is null,'policy revision change denies old grant');
reset role;
update private.memory_eligibility_policies set revision='LOCAL_MATURE' where purpose='MATURE_VIEW';
delete from auth.sessions where id='33333333-3333-4333-8333-333333333333';
set role authenticated;
select pg_temp.ok(public.read_memory_publication(current_setting('test.viewer.board')::uuid) is null,'deleted session denies still-unexpired claims');
reset role;
insert into auth.sessions(id,user_id) values('33333333-3333-4333-8333-333333333333','77777777-7777-4777-8777-777777777777');
set role authenticated;
select pg_temp.ok(public.read_memory_publication(current_setting('test.viewer.board')::uuid) is null,'session of another user cannot supply viewer identity');
reset role;
update auth.sessions set user_id='88888888-8888-4888-8888-888888888888' where id='33333333-3333-4333-8333-333333333333';
update private.memory_content_reviews set rating='BLOCKED' where publication_id=current_setting('test.viewer.board')::uuid;
set role authenticated;
select pg_temp.ok(public.read_memory_publication(current_setting('test.viewer.board')::uuid) is null,'mature eligibility does not override BLOCKED');
reset role;
update private.memory_content_reviews set rating='MATURE',snapshot_hash=repeat('0',64) where publication_id=current_setting('test.viewer.board')::uuid;
set role authenticated;
select pg_temp.ok(public.read_memory_publication(current_setting('test.viewer.board')::uuid) is null,'mature eligibility does not override stale review hash');
reset role;
