create function pg_temp.ok(value boolean,label text) returns void language plpgsql as $$begin if value is distinct from true then raise exception 'FAIL: %',label;end if;raise notice 'PASS: %',label;end $$;
create function pg_temp.fails(statement text,expected text,label text) returns void language plpgsql as $$begin begin execute statement;exception when others then if position(expected in sqlerrm)>0 then perform pg_temp.ok(true,label);return;end if;raise;end;raise exception 'Unexpected success: %',label;end $$;
select pg_temp.fails($q$select private.require_memory_eligibility('11111111-1111-4111-8111-111111111111','CLOUD_WRITE')$q$,'ELIGIBILITY_POLICY_UNAVAILABLE','eligibility defaults closed');
update private.memory_eligibility_policies set enabled=true,revision='SYNTHETIC_ONLY';
select pg_temp.fails($q$select private.require_memory_eligibility('11111111-1111-4111-8111-111111111111','CLOUD_WRITE')$q$,'ELIGIBILITY_REQUIRED','identity receipt does not grant eligibility');
insert into private.memory_eligibility_evidence values('11111111-1111-4111-8111-111111111111','CLOUD_WRITE','SYNTHETIC_ONLY','GRANTED',gen_random_uuid(),clock_timestamp()+interval '1 hour',1);
select pg_temp.ok(private.require_memory_eligibility('11111111-1111-4111-8111-111111111111','CLOUD_WRITE')=1,'exact live evidence accepted');
select pg_temp.fails($q$select private.require_memory_eligibility('22222222-2222-4222-8222-222222222222','CLOUD_WRITE')$q$,'ELIGIBILITY_REQUIRED','other account denied');
select pg_temp.fails($q$select private.require_memory_eligibility('11111111-1111-4111-8111-111111111111','MATURE_VIEW')$q$,'ELIGIBILITY_REQUIRED','cloud eligibility gives no mature access');
begin;
update private.memory_eligibility_evidence set state='REVOKED';
select pg_temp.fails($q$select private.require_memory_eligibility('11111111-1111-4111-8111-111111111111','CLOUD_WRITE')$q$,'ELIGIBILITY_REQUIRED','revoked evidence denied');
rollback;
begin;
update private.memory_eligibility_evidence set expires_at=clock_timestamp()-interval '1 second';
select pg_temp.fails($q$select private.require_memory_eligibility('11111111-1111-4111-8111-111111111111','CLOUD_WRITE')$q$,'ELIGIBILITY_EXPIRED','expired evidence denied');
rollback;
begin;
update private.memory_eligibility_policies set revision='CHANGED';
select pg_temp.fails($q$select private.require_memory_eligibility('11111111-1111-4111-8111-111111111111','CLOUD_WRITE')$q$,'ELIGIBILITY_POLICY_CHANGED','old policy evidence denied');
rollback;
set role authenticated;
select pg_temp.fails('select * from private.memory_eligibility_evidence','permission denied','client cannot read evidence');
select pg_temp.fails($q$update private.memory_eligibility_evidence set state='GRANTED'$q$,'permission denied','client cannot grant eligibility');
reset role;
set role service_role;
select pg_temp.fails($q$update private.memory_eligibility_evidence set state='GRANTED'$q$,'permission denied','service client has no direct issuer access');
reset role;
