create function pg_temp.ok(value boolean,label text) returns void language plpgsql as $$begin if value is distinct from true then raise exception 'FAIL: %',label;end if;raise notice 'PASS: %',label;end $$;
create function pg_temp.fails(statement text,expected text,label text) returns void language plpgsql as $$begin begin execute statement;exception when others then if position(expected in sqlerrm)>0 then perform pg_temp.ok(true,label);return;end if;raise;end;raise exception 'Unexpected success: %',label;end $$;
update private.memory_publication_settings set writes_enabled=true,minihomes_enabled=true,policy_revision='ELIGIBILITY_LOCAL_PUBLIC';
select set_config('request.jwt.claim.sub','77777777-7777-4777-8777-777777777777',false);
select set_config('test.public.selection','{"nickname":"Synthetic public","bio":"","entries":[]}',false);
set role authenticated;
select pg_temp.fails($q$select public.prepare_memory_minihome(0,current_setting('test.public.selection')::jsonb)$q$,'ELIGIBILITY_POLICY_UNAVAILABLE','public eligibility defaults disabled');
reset role;
update private.memory_eligibility_policies set enabled=true,revision='LOCAL_PUBLIC' where purpose='PUBLIC_PUBLISH';
update private.memory_eligibility_evidence set state='GRANTED',expires_at=clock_timestamp()+interval '1 hour' where purpose='CLOUD_WRITE';
set role authenticated;
select pg_temp.fails($q$select public.prepare_memory_minihome(0,current_setting('test.public.selection')::jsonb)$q$,'ELIGIBILITY_REQUIRED','private cloud grant does not permit public preparation');
reset role;
insert into private.memory_eligibility_evidence values('77777777-7777-4777-8777-777777777777','PUBLIC_PUBLISH','LOCAL_PUBLIC','GRANTED',gen_random_uuid(),clock_timestamp()+interval '1 hour',1);
-- A real valid home requires a readable board; seed a synthetic design source.
begin;
insert into public.memory_boards(id,user_id,title,client_updated_at) values('55555555-5555-4555-8555-555555555550','77777777-7777-4777-8777-777777777777','Synthetic public board',now());
insert into public.memory_cards(id,user_id,catalog_anime_id,title_snapshot,status,client_updated_at) values('55555555-5555-4555-8555-555555555551','77777777-7777-4777-8777-777777777777','anime:55555555-5555-4555-8555-555555555551','Synthetic design','COMPLETE_PRIVATE',now());
insert into public.memory_visual_assets(id,user_id,card_id,asset_type,state,is_current,rights_basis,design_spec,client_updated_at) values('55555555-5555-4555-8555-555555555552','77777777-7777-4777-8777-777777777777','55555555-5555-4555-8555-555555555551','SYSTEM_DESIGN','READY',true,'SYSTEM_GENERATED','{"version":1,"templateId":"memory-gradient","titleLayout":"CENTER","paletteId":"synthetic","patternSeed":"synthetic","genreTokens":[]}',now());
insert into public.memory_board_cards(id,user_id,board_id,card_id,position_key,client_updated_at) values(gen_random_uuid(),'77777777-7777-4777-8777-777777777777','55555555-5555-4555-8555-555555555550','55555555-5555-4555-8555-555555555551','0',now());
commit;
update private.memory_publication_settings set reads_enabled=true,content_policy_revision='LOCAL_CONTENT';
set role authenticated;
select set_config('test.board.preview',public.prepare_memory_publication('55555555-5555-4555-8555-555555555550',0,'{"title":"Synthetic board","description":"","cards":[{"cardId":"55555555-5555-4555-8555-555555555551","fields":[]}]}')::text,false);
select public.publish_memory_publication((current_setting('test.board.preview')::jsonb->>'id')::uuid,(current_setting('test.board.preview')::jsonb->>'revision')::bigint,current_setting('test.board.preview')::jsonb->>'reviewHash','ELIGIBILITY_LOCAL_PUBLIC',gen_random_uuid());
reset role;
insert into private.memory_content_reviews(publication_id,snapshot_hash,rating,reviewed_by,policy_revision)
select id,encode(sha256(convert_to(published_snapshot::text,'UTF8')),'hex'),'GENERAL','77777777-7777-4777-8777-777777777777','LOCAL_CONTENT' from private.memory_publications where id=(current_setting('test.board.preview')::jsonb->>'id')::uuid;
select set_config('test.public.selection',jsonb_build_object('nickname','Synthetic public','bio','','entries',jsonb_build_array(jsonb_build_object('publicationId',current_setting('test.board.preview')::jsonb->>'id')))::text,false);
set role authenticated;
select set_config('test.public.preview',public.prepare_memory_minihome(0,current_setting('test.public.selection')::jsonb)::text,false);
reset role;
update private.memory_eligibility_evidence set state='REVOKED' where purpose='PUBLIC_PUBLISH';
set role authenticated;
select pg_temp.fails($q$select public.publish_memory_minihome((current_setting('test.public.preview')::jsonb->>'revision')::bigint,current_setting('test.public.preview')::jsonb->>'reviewHash','ELIGIBILITY_LOCAL_PUBLIC','77777777-7777-4777-8777-777777777980')$q$,'ELIGIBILITY_REQUIRED','revocation after preview prevents publish');
reset role;
update private.memory_eligibility_evidence set state='GRANTED' where purpose='PUBLIC_PUBLISH';
set role authenticated;
select set_config('test.public.published',public.publish_memory_minihome((current_setting('test.public.preview')::jsonb->>'revision')::bigint,current_setting('test.public.preview')::jsonb->>'reviewHash','ELIGIBILITY_LOCAL_PUBLIC','77777777-7777-4777-8777-777777777980')::text,false);
select pg_temp.ok((current_setting('test.public.published')::jsonb->>'published')::boolean,'eligible owner publishes existing preview');
reset role;
update private.memory_eligibility_evidence set state='REVOKED' where purpose='PUBLIC_PUBLISH';
set role authenticated;
select pg_temp.fails($q$select public.prepare_memory_minihome((current_setting('test.public.published')::jsonb->>'revision')::bigint,current_setting('test.public.selection')::jsonb)$q$,'ELIGIBILITY_REQUIRED','revoked public grant blocks new preview');
select pg_temp.ok((public.revoke_memory_minihome((current_setting('test.public.published')::jsonb->>'revision')::bigint)->>'published')::boolean=false,'public grant revocation does not prevent withdrawal');
reset role;
select pg_temp.ok((select published_selection is null from private.memory_minihomes where user_id='77777777-7777-4777-8777-777777777777'),'withdrawal actually removes published home selection');
insert into private.memory_minihomes(user_id) values('88888888-8888-4888-8888-888888888888') on conflict do nothing;
select set_config('test.block.home',(select id::text from private.memory_minihomes where user_id='88888888-8888-4888-8888-888888888888'),false);
set role authenticated;
select pg_temp.ok((public.set_memory_relationship(current_setting('test.block.home')::uuid,'block')->>'blocked')::boolean,'public eligibility revocation does not prevent blocking');
select pg_temp.ok((public.set_memory_relationship(current_setting('test.block.home')::uuid,'unfollow')->>'following')::boolean=false,'public eligibility revocation does not prevent unfollowing');
reset role;
select pg_temp.ok(private.require_publication_writer() is not null,'shared writer remains separate from new publishing eligibility');
